version: '3.4'

services:
    mongo:
        hostname: mongo
        container_name: mongo
        image: mongo:latest
        expose:
            - 27017
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_DATABASE
            - MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD
            - MONGO_USERNAME
            - MONGO_PASSWORD
        volumes:
            - mongo_storage:/data/db
            - $PWD/_docker/mongo/replica.key:/data/replica.key
            - $PWD/_docker/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
            
        entrypoint:
            - bash
            - -c
            - |
                echo "###############################"
                chmod 400 /data/replica.key
                chown 999:999 /data/replica.key
                ls -la /data/
                echo "###############################"
                exec docker-entrypoint.sh $$@     
        command: mongod --bind_ip_all --replSet replicaSet --keyFile /data/replica.key

        
    # redis:
    #     container_name: redis
    #     image: redis:alpine
    #     ports:
    #         - 6379:6379
    #     environment:
    #         - REDIS_SECRET
    #     command: redis-server --requirepass ${REDIS_SECRET}

volumes:
    mongo_storage:
            
