version: '3.2'

services:
    mongo:
        container_name: 'mongo'
        image: 'mongo:latest'
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_DATABASE
            - MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD
            - MONGO_USERNAME
            - MONGO_PASSWORD
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            - mongodb_data_container:/data/db
            - $PWD/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh

    redis:
        container_name: 'redis'
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        environment:
             - REDIS_SECRET
        command: redis-server --requirepass ${REDIS_SECRET}

volumes:
    mongodb_data_container:
            
