services:    
    backend:
        profiles:
            - backend 
        build:
            context: ../../code/web
            dockerfile: "@backend/Dockerfile"
        container_name: backend
        restart: always
        depends_on:
            - postgres
            - redis
        env_file:
            - .env
        ports:
            - "8080:8080"

    postgres:
        hostname: postgres 
        container_name: postgres
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DATABASE
        ports:
            - 5432:5432
        volumes:
            - postgres_storage:/var/lib/postgresql/data
            - $PWD/postgres/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh

    redis:
        hostname: redis
        container_name: redis
        image: redis:alpine
        ports:
            - 6379:6379
        environment:
            - REDIS_SECRET
        command: redis-server --requirepass ${REDIS_SECRET}

    localstack:
        hostname: localstack
        container_name: localstack
        image: localstack/localstack
        ports:
            - "127.0.0.1:4566:4566"            # LocalStack Gateway
            - "127.0.0.1:4510-4559:4510-4559"  # external services port range
        environment:
            # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
            - DEBUG=${DEBUG:-0}
        volumes:
            - localstack_storage:/var/lib/localstack
            - "/var/run/docker.sock:/var/run/docker.sock"


volumes:
    postgres_storage:
    localstack_storage:
            
