## This is meant to be built from ~/code
## docker build -f backend/dockerfile --progress plain --no-cache  -t drilldown .

FROM node:18

# Create app directory
WORKDIR /usr/src/app

# Copy necessary source code
COPY ./package.json ./
COPY ./yarn.lock ./
COPY ./tsconfig.json ./
ADD ./backend ./backend/
ADD ./interfaces ./interfaces/

RUN ls -a 

# Install app dependencies
RUN yarn install

CMD ["yarn", "start:backend"]