# This is meant to be built from ~/code/web

FROM node:18-bullseye AS backend

WORKDIR /usr/src/app

RUN corepack enable && corepack prepare yarn@4.7.0 --activate

COPY .yarnrc.yml ./
COPY package.json yarn.lock ./
COPY tsconfig.json ./

COPY @common ./@common
COPY @backend ./@backend

RUN yarn install

WORKDIR /usr/src/app/@backend

RUN yarn build

EXPOSE 3000

ENV NODE_ENV=production

CMD ["node", "build/src/server.js"]
