name: Frontend Deploy

on:
  pull_request:
    branches: [ "master" ]

env: 
  FRONTEND_BUILD_BUCKET: "frontend-build-bucket"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build React App
        run: |
          cd code
          yarn install
          cd frontend 
          yarn run build:prod
      - name: Deploy build to S3 bucket
        run: aws s3 sync ./build/ s3://$FRONTEND_BUILD_BUCKET --delete